// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID      int32
	Lim     int32
	Balance int32
}

type Transaction struct {
	ID          int32
	AccountID   int32
	Amount      int32
	Type        string
	Description string
	Date        pgtype.Timestamp
}
